/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.musemo.view;

/**
 *
 * @author acer
 */
public class Musemo extends javax.swing.JFrame {

    private java.awt.CardLayout cardLayout;
    
    /**
     * Creates new form Musemo
     */
    public Musemo() {
        initComponents();
        initializeLayout();
        startProgress();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHomeScreen = new javax.swing.JPanel();
        lblHomePageHeader = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnlHome = new javax.swing.JPanel();
        lblHomePageWelcome = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnAdminLogin = new javax.swing.JButton();
        pnlAboutPage = new javax.swing.JPanel();
        pnlAdminLoginScreen = new javax.swing.JPanel();
        pnlAdminDashboardScreen = new javax.swing.JPanel();
        pnlAbout = new javax.swing.JPanel();
        pnlLoadingScreen = new javax.swing.JPanel();
        lblloading = new javax.swing.JLabel();
        prgBarLoadingScreen = new javax.swing.JProgressBar();
        lblLoadingTitle = new javax.swing.JLabel();
        lblLoadingScreenGif = new javax.swing.JLabel();

        pnlHomeScreen.setBackground(new java.awt.Color(1, 0, 59));
        pnlHomeScreen.setMaximumSize(new java.awt.Dimension(1300, 700));
        pnlHomeScreen.setMinimumSize(new java.awt.Dimension(1300, 700));

        lblHomePageHeader.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/musemo/resources/AllPageHeader.png"))); // NOI18N

        jTabbedPane1.setBackground(new java.awt.Color(1, 127, 132));
        jTabbedPane1.setMaximumSize(new java.awt.Dimension(1300, 500));
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(1300, 500));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(1300, 500));

        pnlHome.setBackground(new java.awt.Color(1, 0, 59));
        pnlHome.setPreferredSize(new java.awt.Dimension(1300, 700));

        lblHomePageWelcome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/musemo/resources/HomePage.png"))); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/musemo/resources/HomePageFooter.png"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(1300, 197));
        jLabel1.setMinimumSize(new java.awt.Dimension(1300, 197));
        jLabel1.setPreferredSize(new java.awt.Dimension(1300, 197));

        btnAdminLogin.setBackground(new java.awt.Color(102, 102, 255));
        btnAdminLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAdminLogin.setText("Admin");
        btnAdminLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlHomeLayout = new javax.swing.GroupLayout(pnlHome);
        pnlHome.setLayout(pnlHomeLayout);
        pnlHomeLayout.setHorizontalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHomeLayout.createSequentialGroup()
                .addComponent(lblHomePageWelcome)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnlHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAdminLogin)
                .addGap(20, 20, 20))
        );
        pnlHomeLayout.setVerticalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHomeLayout.createSequentialGroup()
                .addComponent(lblHomePageWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHomeLayout.createSequentialGroup()
                        .addComponent(btnAdminLogin)
                        .addGap(18, 18, 18)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Home", pnlHome);

        pnlAboutPage.setBackground(new java.awt.Color(9, 1, 59));
        pnlAboutPage.setPreferredSize(new java.awt.Dimension(1300, 700));

        javax.swing.GroupLayout pnlAboutPageLayout = new javax.swing.GroupLayout(pnlAboutPage);
        pnlAboutPage.setLayout(pnlAboutPageLayout);
        pnlAboutPageLayout.setHorizontalGroup(
            pnlAboutPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1300, Short.MAX_VALUE)
        );
        pnlAboutPageLayout.setVerticalGroup(
            pnlAboutPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 525, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("About", pnlAboutPage);

        javax.swing.GroupLayout pnlHomeScreenLayout = new javax.swing.GroupLayout(pnlHomeScreen);
        pnlHomeScreen.setLayout(pnlHomeScreenLayout);
        pnlHomeScreenLayout.setHorizontalGroup(
            pnlHomeScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblHomePageHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlHomeScreenLayout.setVerticalGroup(
            pnlHomeScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHomeScreenLayout.createSequentialGroup()
                .addComponent(lblHomePageHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE))
        );

        pnlAdminLoginScreen.setMaximumSize(new java.awt.Dimension(1300, 700));
        pnlAdminLoginScreen.setMinimumSize(new java.awt.Dimension(1300, 700));

        javax.swing.GroupLayout pnlAdminLoginScreenLayout = new javax.swing.GroupLayout(pnlAdminLoginScreen);
        pnlAdminLoginScreen.setLayout(pnlAdminLoginScreenLayout);
        pnlAdminLoginScreenLayout.setHorizontalGroup(
            pnlAdminLoginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1300, Short.MAX_VALUE)
        );
        pnlAdminLoginScreenLayout.setVerticalGroup(
            pnlAdminLoginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        pnlAdminDashboardScreen.setMaximumSize(new java.awt.Dimension(1300, 700));
        pnlAdminDashboardScreen.setMinimumSize(new java.awt.Dimension(1300, 700));
        pnlAdminDashboardScreen.setPreferredSize(new java.awt.Dimension(1300, 700));

        javax.swing.GroupLayout pnlAdminDashboardScreenLayout = new javax.swing.GroupLayout(pnlAdminDashboardScreen);
        pnlAdminDashboardScreen.setLayout(pnlAdminDashboardScreenLayout);
        pnlAdminDashboardScreenLayout.setHorizontalGroup(
            pnlAdminDashboardScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        pnlAdminDashboardScreenLayout.setVerticalGroup(
            pnlAdminDashboardScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        pnlAbout.setMaximumSize(new java.awt.Dimension(1300, 700));
        pnlAbout.setMinimumSize(new java.awt.Dimension(1300, 700));
        pnlAbout.setPreferredSize(new java.awt.Dimension(1300, 700));

        javax.swing.GroupLayout pnlAboutLayout = new javax.swing.GroupLayout(pnlAbout);
        pnlAbout.setLayout(pnlAboutLayout);
        pnlAboutLayout.setHorizontalGroup(
            pnlAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        pnlAboutLayout.setVerticalGroup(
            pnlAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(java.awt.Color.black);
        setIconImages(null);
        setLocation(new java.awt.Point(100, 50));
        setMaximumSize(new java.awt.Dimension(1300, 720));
        setMinimumSize(new java.awt.Dimension(1300, 720));
        setPreferredSize(new java.awt.Dimension(1300, 720));
        setResizable(false);

        pnlLoadingScreen.setBackground(new java.awt.Color(0, 0, 0));
        pnlLoadingScreen.setForeground(new java.awt.Color(255, 255, 255));
        pnlLoadingScreen.setToolTipText("");
        pnlLoadingScreen.setMaximumSize(new java.awt.Dimension(1300, 700));
        pnlLoadingScreen.setMinimumSize(new java.awt.Dimension(1300, 700));
        pnlLoadingScreen.setPreferredSize(new java.awt.Dimension(1300, 700));
        pnlLoadingScreen.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblloading.setFont(new java.awt.Font("Calibri", 1, 48)); // NOI18N
        lblloading.setForeground(new java.awt.Color(255, 255, 255));
        lblloading.setText("Loading.......");
        pnlLoadingScreen.add(lblloading, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 610, 350, -1));

        prgBarLoadingScreen.setBackground(new java.awt.Color(255, 51, 0));
        prgBarLoadingScreen.setToolTipText("");
        pnlLoadingScreen.add(prgBarLoadingScreen, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 580, 370, 20));

        lblLoadingTitle.setBackground(new java.awt.Color(255, 255, 255));
        lblLoadingTitle.setFont(new java.awt.Font("Monotype Corsiva", 3, 90)); // NOI18N
        lblLoadingTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblLoadingTitle.setText("MUSEMO");
        pnlLoadingScreen.add(lblLoadingTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 620, 200));

        lblLoadingScreenGif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/musemo/resources/loading screen.gif"))); // NOI18N
        pnlLoadingScreen.add(lblLoadingScreenGif, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 1080, 750));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlLoadingScreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlLoadingScreen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdminLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdminLoginActionPerformed
    /**
     * Initializes the layout of the application by setting up the CardLayout
     * and adding panels for different screens. Each panel is uniquely
     * identified for easy navigation between screens.
     */
    private void initializeLayout() {
        cardLayout = new java.awt.CardLayout();
        getContentPane().setLayout(cardLayout);

        // Add panels with unique identifiers
        getContentPane().add(pnlLoadingScreen, "LoadingScreen");
        getContentPane().add(pnlAdminLoginScreen, "AdminLoginScreen");
        getContentPane().add(pnlHomeScreen, "HomeScreen");
        getContentPane().add(pnlAdminDashboardScreen, "DashboardScreen");
        getContentPane().add(pnlAbout, "AboutScreen");


        // Start with the loading screen
        loadScreen("LoadingScreen");
    }
    /**
     * Switches the application screen to the specified screen name.
     *
     * @param screenName The name of the screen to display.
     */
    private void loadScreen(String screenName) {
        cardLayout.show(getContentPane(), screenName);
    }
    /**
     * Simulates the loading progress using a SwingWorker thread. Updates a
     * progress bar incrementally and switches to the login screen upon
     * completion.
     */
    private void startProgress() {
        javax.swing.SwingWorker<Void, Integer> worker = new javax.swing.SwingWorker<>() {
            @Override
            protected Void doInBackground() throws Exception {
                for (int i = 0; i <= 100; i++) {
                    Thread.sleep(100); // Simulated delay for progress bar
                    publish(i); // Publish progress
                }
                return null;
            }

            @Override
            protected void process(java.util.List<Integer> chunks) {
                int progress = chunks.get(chunks.size() - 1);
                prgBarLoadingScreen.setValue(progress);
            }

            @Override
            protected void done() {
                loadScreen("HomeScreen"); // Switch to login screen
            }
        };
        worker.execute(); // Start the worker thread
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Musemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Musemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Musemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Musemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Musemo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdminLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblHomePageHeader;
    private javax.swing.JLabel lblHomePageWelcome;
    private javax.swing.JLabel lblLoadingScreenGif;
    private javax.swing.JLabel lblLoadingTitle;
    private javax.swing.JLabel lblloading;
    private javax.swing.JPanel pnlAbout;
    private javax.swing.JPanel pnlAboutPage;
    private javax.swing.JPanel pnlAdminDashboardScreen;
    private javax.swing.JPanel pnlAdminLoginScreen;
    private javax.swing.JPanel pnlHome;
    private javax.swing.JPanel pnlHomeScreen;
    private javax.swing.JPanel pnlLoadingScreen;
    private javax.swing.JProgressBar prgBarLoadingScreen;
    // End of variables declaration//GEN-END:variables
}
