package com.musemo.view;

import com.musemo.controller.ValidationUtil;
import com.musemo.model.ObjectModel;
import java.awt.Color;
import java.util.LinkedList;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Viom Shrestha
 */
public class Musemo extends javax.swing.JFrame {

    private List<ObjectModel> objectList;
    private java.awt.CardLayout cardLayout;
    private final ValidationUtil validationUtil;
    private final Color errorColor = new Color(255, 51, 0);
    private final Color greenColor = new Color(0, 255, 102);
    
    /**
     * Creates new form Musemo
     */
    public Musemo() {
        initComponents();
        validationUtil = new ValidationUtil();
        initializeLayout(); // Sets up CardLayout and pages
        initializaData(); // Initialize Objct data and Object table
        startProgress(); // Simulates the loading bar
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHomeScreen = new javax.swing.JPanel();
        lblHomePageHeader = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnlHome = new javax.swing.JPanel();
        lblHomePageWelcome = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnAdminLogin = new javax.swing.JButton();
        pnlAboutPage = new javax.swing.JPanel();
        lblFounderMessage = new javax.swing.JLabel();
        lblAboutUsTitle = new javax.swing.JLabel();
        lblAboutUsSlogan = new javax.swing.JLabel();
        lblFounderHeader = new javax.swing.JLabel();
        pnlAdminLoginScreen = new javax.swing.JPanel();
        btnBackToHome = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtFldAdminLogin = new javax.swing.JTextField();
        pwdFldAdminLogin = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        lblLoginError = new javax.swing.JLabel();
        lblLoginIcon = new javax.swing.JLabel();
        pnlAdminDashboardScreen = new javax.swing.JPanel();
        lblHomePageHeader1 = new javax.swing.JLabel();
        lblDashboardTitle = new javax.swing.JLabel();
        lblDashboard = new javax.swing.JLabel();
        btnManageObjects = new javax.swing.JButton();
        pnlManageObjects = new javax.swing.JPanel();
        lblManageBojectsHeader = new javax.swing.JLabel();
        spTblObjects = new javax.swing.JScrollPane();
        tblObject = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        pnlForm = new javax.swing.JPanel();
        txtFldObjectId = new javax.swing.JTextField();
        txtFldCondition = new javax.swing.JTextField();
        txtFldObjectName = new javax.swing.JTextField();
        txtFldObjectType = new javax.swing.JTextField();
        txtFldCreator = new javax.swing.JTextField();
        txtFldStatus = new javax.swing.JTextField();
        txtFldOrigin = new javax.swing.JTextField();
        txtFldRoom = new javax.swing.JTextField();
        txtFldFloor = new javax.swing.JTextField();
        btnAddObject = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        lblErrorMsgObjectName = new javax.swing.JLabel();
        lblErrorMsgObjectId = new javax.swing.JLabel();
        lblErrorMsgObjectType = new javax.swing.JLabel();
        lblErrorMsgCreator = new javax.swing.JLabel();
        lblErrorMsgStatus = new javax.swing.JLabel();
        lblErrorMsgOrigin = new javax.swing.JLabel();
        lblErrorMsgCondition = new javax.swing.JLabel();
        lblErrorMsgFloor = new javax.swing.JLabel();
        lblErrorMsgRoomNo = new javax.swing.JLabel();
        pnlLoadingScreen = new javax.swing.JPanel();
        lblloading = new javax.swing.JLabel();
        prgBarLoadingScreen = new javax.swing.JProgressBar();
        lblLoadingTitle = new javax.swing.JLabel();
        lblLoadingScreenGif = new javax.swing.JLabel();
        lblCopyRight = new javax.swing.JLabel();

        pnlHomeScreen.setBackground(new java.awt.Color(1, 0, 59));
        pnlHomeScreen.setMaximumSize(new java.awt.Dimension(1300, 700));
        pnlHomeScreen.setMinimumSize(new java.awt.Dimension(1300, 700));

        lblHomePageHeader.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/musemo/resources/AllPageHeader.png"))); // NOI18N

        jTabbedPane1.setBackground(new java.awt.Color(1, 127, 132));
        jTabbedPane1.setMaximumSize(new java.awt.Dimension(1300, 500));
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(1300, 500));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(1300, 500));

        pnlHome.setBackground(new java.awt.Color(1, 0, 59));
        pnlHome.setPreferredSize(new java.awt.Dimension(1300, 700));

        lblHomePageWelcome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/musemo/resources/HomePage.png"))); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/musemo/resources/HomePageFooter.png"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(1300, 197));
        jLabel1.setMinimumSize(new java.awt.Dimension(1300, 197));
        jLabel1.setPreferredSize(new java.awt.Dimension(1300, 197));

        btnAdminLogin.setBackground(new java.awt.Color(102, 102, 255));
        btnAdminLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAdminLogin.setText("Admin");
        btnAdminLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlHomeLayout = new javax.swing.GroupLayout(pnlHome);
        pnlHome.setLayout(pnlHomeLayout);
        pnlHomeLayout.setHorizontalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHomeLayout.createSequentialGroup()
                .addComponent(lblHomePageWelcome)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnlHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAdminLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        pnlHomeLayout.setVerticalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHomeLayout.createSequentialGroup()
                .addComponent(lblHomePageWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlHomeLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(11, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHomeLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAdminLogin)
                        .addGap(39, 39, 39))))
        );

        jTabbedPane1.addTab("Home", pnlHome);

        pnlAboutPage.setBackground(new java.awt.Color(9, 1, 59));
        pnlAboutPage.setPreferredSize(new java.awt.Dimension(1300, 700));

        lblFounderMessage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/musemo/resources/AboutPageMessage.jpg"))); // NOI18N

        lblAboutUsTitle.setBackground(new java.awt.Color(255, 255, 255));
        lblAboutUsTitle.setFont(new java.awt.Font("Poor Richard", 1, 36)); // NOI18N
        lblAboutUsTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblAboutUsTitle.setText("About Us");

        lblAboutUsSlogan.setBackground(new java.awt.Color(255, 255, 255));
        lblAboutUsSlogan.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        lblAboutUsSlogan.setForeground(new java.awt.Color(255, 255, 255));
        lblAboutUsSlogan.setText("\"Preserving the past to inspire the future, our museum is a gateway to history, culture, and discovery.\"");

        lblFounderHeader.setBackground(new java.awt.Color(255, 255, 255));
        lblFounderHeader.setFont(new java.awt.Font("Poor Richard", 1, 36)); // NOI18N
        lblFounderHeader.setForeground(new java.awt.Color(255, 255, 255));
        lblFounderHeader.setText("Message from the Founder:");

        javax.swing.GroupLayout pnlAboutPageLayout = new javax.swing.GroupLayout(pnlAboutPage);
        pnlAboutPage.setLayout(pnlAboutPageLayout);
        pnlAboutPageLayout.setHorizontalGroup(
            pnlAboutPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAboutPageLayout.createSequentialGroup()
                .addGroup(pnlAboutPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFounderMessage)
                    .addGroup(pnlAboutPageLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(lblFounderHeader)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAboutPageLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlAboutPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAboutPageLayout.createSequentialGroup()
                        .addComponent(lblAboutUsTitle)
                        .addGap(577, 577, 577))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAboutPageLayout.createSequentialGroup()
                        .addComponent(lblAboutUsSlogan)
                        .addGap(216, 216, 216))))
        );
        pnlAboutPageLayout.setVerticalGroup(
            pnlAboutPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAboutPageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAboutUsTitle)
                .addGap(18, 18, 18)
                .addComponent(lblAboutUsSlogan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(lblFounderHeader)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFounderMessage)
                .addGap(35, 35, 35))
        );

        jTabbedPane1.addTab("About", pnlAboutPage);

        javax.swing.GroupLayout pnlHomeScreenLayout = new javax.swing.GroupLayout(pnlHomeScreen);
        pnlHomeScreen.setLayout(pnlHomeScreenLayout);
        pnlHomeScreenLayout.setHorizontalGroup(
            pnlHomeScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblHomePageHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlHomeScreenLayout.setVerticalGroup(
            pnlHomeScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHomeScreenLayout.createSequentialGroup()
                .addComponent(lblHomePageHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE))
        );

        pnlAdminLoginScreen.setBackground(new java.awt.Color(1, 0, 59));
        pnlAdminLoginScreen.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlAdminLoginScreen.setMaximumSize(new java.awt.Dimension(900, 600));
        pnlAdminLoginScreen.setMinimumSize(new java.awt.Dimension(900, 600));

        btnBackToHome.setBackground(new java.awt.Color(255, 255, 255));
        btnBackToHome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBackToHome.setForeground(new java.awt.Color(102, 0, 153));
        btnBackToHome.setText("Back");
        btnBackToHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackToHomeActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Admin Login");

        txtFldAdminLogin.setBackground(new java.awt.Color(1, 0, 59));
        txtFldAdminLogin.setForeground(new java.awt.Color(153, 153, 255));
        txtFldAdminLogin.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255), 2), "Username", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(153, 153, 255))); // NOI18N
        txtFldAdminLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFldAdminLoginActionPerformed(evt);
            }
        });

        pwdFldAdminLogin.setBackground(new java.awt.Color(1, 0, 59));
        pwdFldAdminLogin.setForeground(new java.awt.Color(234, 192, 32));
        pwdFldAdminLogin.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255), 2), "Password", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(153, 153, 255))); // NOI18N
        pwdFldAdminLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdFldAdminLoginActionPerformed(evt);
            }
        });

        btnLogin.setBackground(new java.awt.Color(255, 255, 255));
        btnLogin.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(0, 0, 0));
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        lblLoginError.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lblLoginError.setForeground(new java.awt.Color(255, 0, 0));
        lblLoginError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblLoginIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/musemo/resources/LoginImg.jpg"))); // NOI18N

        javax.swing.GroupLayout pnlAdminLoginScreenLayout = new javax.swing.GroupLayout(pnlAdminLoginScreen);
        pnlAdminLoginScreen.setLayout(pnlAdminLoginScreenLayout);
        pnlAdminLoginScreenLayout.setHorizontalGroup(
            pnlAdminLoginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdminLoginScreenLayout.createSequentialGroup()
                .addGroup(pnlAdminLoginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAdminLoginScreenLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(pnlAdminLoginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBackToHome, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlAdminLoginScreenLayout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addGroup(pnlAdminLoginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtFldAdminLogin)
                                    .addComponent(pwdFldAdminLogin)
                                    .addComponent(btnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                                    .addGroup(pnlAdminLoginScreenLayout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addComponent(jLabel2)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE))
                    .addGroup(pnlAdminLoginScreenLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblLoginError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(lblLoginIcon))
        );
        pnlAdminLoginScreenLayout.setVerticalGroup(
            pnlAdminLoginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdminLoginScreenLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btnBackToHome)
                .addGap(87, 87, 87)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLoginError, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFldAdminLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(pwdFldAdminLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(lblLoginIcon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pnlAdminDashboardScreen.setBackground(new java.awt.Color(1, 0, 59));
        pnlAdminDashboardScreen.setMaximumSize(new java.awt.Dimension(1300, 700));
        pnlAdminDashboardScreen.setMinimumSize(new java.awt.Dimension(1300, 700));
        pnlAdminDashboardScreen.setPreferredSize(new java.awt.Dimension(1300, 700));

        lblHomePageHeader1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/musemo/resources/AllPageHeader.png"))); // NOI18N

        lblDashboardTitle.setFont(new java.awt.Font("Poor Richard", 1, 36)); // NOI18N
        lblDashboardTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblDashboardTitle.setText("Dashboard");

        lblDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/musemo/resources/AdminDashBoard.jpg"))); // NOI18N

        btnManageObjects.setBackground(new java.awt.Color(255, 255, 255));
        btnManageObjects.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnManageObjects.setForeground(new java.awt.Color(0, 0, 0));
        btnManageObjects.setText("Manage Objects");
        btnManageObjects.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageObjectsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAdminDashboardScreenLayout = new javax.swing.GroupLayout(pnlAdminDashboardScreen);
        pnlAdminDashboardScreen.setLayout(pnlAdminDashboardScreenLayout);
        pnlAdminDashboardScreenLayout.setHorizontalGroup(
            pnlAdminDashboardScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblHomePageHeader1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlAdminDashboardScreenLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblDashboardTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnManageObjects)
                .addGap(47, 47, 47))
            .addGroup(pnlAdminDashboardScreenLayout.createSequentialGroup()
                .addComponent(lblDashboard)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlAdminDashboardScreenLayout.setVerticalGroup(
            pnlAdminDashboardScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdminDashboardScreenLayout.createSequentialGroup()
                .addComponent(lblHomePageHeader1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(pnlAdminDashboardScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDashboardTitle)
                    .addComponent(btnManageObjects))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDashboard)
                .addGap(18, 18, 18))
        );

        pnlManageObjects.setBackground(new java.awt.Color(1, 0, 59));
        pnlManageObjects.setMaximumSize(new java.awt.Dimension(1300, 700));
        pnlManageObjects.setMinimumSize(new java.awt.Dimension(1300, 700));
        pnlManageObjects.setPreferredSize(new java.awt.Dimension(1300, 700));

        lblManageBojectsHeader.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/musemo/resources/AllPageHeader.png"))); // NOI18N

        tblObject.setBackground(new java.awt.Color(153, 153, 255));
        tblObject.setForeground(new java.awt.Color(0, 0, 0));
        tblObject.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Object ID", "Object Name", "Object Type", "Creator", "Status", "Origin", "Condition", "Floor", "Room"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Short.class, java.lang.Short.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblObject.setGridColor(new java.awt.Color(0, 0, 0));
        tblObject.setSelectionBackground(new java.awt.Color(102, 102, 255));
        tblObject.setSelectionForeground(new java.awt.Color(51, 255, 0));
        tblObject.setShowGrid(true);
        tblObject.setShowHorizontalLines(true);
        tblObject.setShowVerticalLines(true);
        tblObject.getTableHeader().setReorderingAllowed(false);
        spTblObjects.setViewportView(tblObject);
        if (tblObject.getColumnModel().getColumnCount() > 0) {
            tblObject.getColumnModel().getColumn(0).setResizable(false);
            tblObject.getColumnModel().getColumn(1).setResizable(false);
            tblObject.getColumnModel().getColumn(2).setResizable(false);
            tblObject.getColumnModel().getColumn(3).setResizable(false);
            tblObject.getColumnModel().getColumn(4).setResizable(false);
            tblObject.getColumnModel().getColumn(5).setResizable(false);
            tblObject.getColumnModel().getColumn(6).setResizable(false);
            tblObject.getColumnModel().getColumn(7).setResizable(false);
            tblObject.getColumnModel().getColumn(8).setResizable(false);
        }
        tblObject.getAccessibleContext().setAccessibleParent(tblObject);

        jLabel3.setFont(new java.awt.Font("Poor Richard", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Object Table");

        pnlForm.setBackground(new java.awt.Color(1, 0, 59));
        pnlForm.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Object Form", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Poor Richard", 1, 18))); // NOI18N
        pnlForm.setMaximumSize(new java.awt.Dimension(1080, 960));
        pnlForm.setMinimumSize(new java.awt.Dimension(1080, 960));
        pnlForm.setPreferredSize(new java.awt.Dimension(900, 300));

        txtFldObjectId.setBackground(new java.awt.Color(0, 0, 0));
        txtFldObjectId.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255)), "Object Id", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        txtFldObjectId.setCaretColor(new java.awt.Color(0, 102, 102));
        txtFldObjectId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFldObjectIdActionPerformed(evt);
            }
        });

        txtFldCondition.setBackground(new java.awt.Color(0, 0, 0));
        txtFldCondition.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255)), "Condition", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        txtFldCondition.setCaretColor(new java.awt.Color(0, 102, 102));
        txtFldCondition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFldConditionActionPerformed(evt);
            }
        });

        txtFldObjectName.setBackground(new java.awt.Color(0, 0, 0));
        txtFldObjectName.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255)), "Object Name", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        txtFldObjectName.setCaretColor(new java.awt.Color(0, 102, 102));
        txtFldObjectName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFldObjectNameActionPerformed(evt);
            }
        });

        txtFldObjectType.setBackground(new java.awt.Color(0, 0, 0));
        txtFldObjectType.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255)), "Object Type", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        txtFldObjectType.setCaretColor(new java.awt.Color(0, 102, 102));
        txtFldObjectType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFldObjectTypeActionPerformed(evt);
            }
        });

        txtFldCreator.setBackground(new java.awt.Color(0, 0, 0));
        txtFldCreator.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255)), "Creator", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        txtFldCreator.setCaretColor(new java.awt.Color(0, 102, 102));
        txtFldCreator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFldCreatorActionPerformed(evt);
            }
        });

        txtFldStatus.setBackground(new java.awt.Color(0, 0, 0));
        txtFldStatus.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255)), "Status", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        txtFldStatus.setCaretColor(new java.awt.Color(0, 102, 102));
        txtFldStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFldStatusActionPerformed(evt);
            }
        });

        txtFldOrigin.setBackground(new java.awt.Color(0, 0, 0));
        txtFldOrigin.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255)), "Origin", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        txtFldOrigin.setCaretColor(new java.awt.Color(0, 102, 102));
        txtFldOrigin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFldOriginActionPerformed(evt);
            }
        });

        txtFldRoom.setBackground(new java.awt.Color(0, 0, 0));
        txtFldRoom.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255)), "Room", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        txtFldRoom.setCaretColor(new java.awt.Color(0, 102, 102));
        txtFldRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFldRoomActionPerformed(evt);
            }
        });

        txtFldFloor.setBackground(new java.awt.Color(0, 0, 0));
        txtFldFloor.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255)), "Floor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        txtFldFloor.setCaretColor(new java.awt.Color(0, 102, 102));
        txtFldFloor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFldFloorActionPerformed(evt);
            }
        });

        btnAddObject.setBackground(new java.awt.Color(0, 255, 102));
        btnAddObject.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAddObject.setForeground(new java.awt.Color(0, 0, 0));
        btnAddObject.setText("Add Object");
        btnAddObject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddObjectActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(0, 255, 102));
        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(0, 0, 0));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(0, 255, 102));
        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(0, 0, 0));
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(0, 255, 102));
        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnClear.setForeground(new java.awt.Color(0, 0, 0));
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlFormLayout = new javax.swing.GroupLayout(pnlForm);
        pnlForm.setLayout(pnlFormLayout);
        pnlFormLayout.setHorizontalGroup(
            pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFormLayout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFormLayout.createSequentialGroup()
                        .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFldObjectId, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFldRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblErrorMsgObjectId, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblErrorMsgRoomNo, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(64, 64, 64)
                        .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlFormLayout.createSequentialGroup()
                                .addComponent(btnAddObject)
                                .addGap(74, 74, 74)
                                .addComponent(btnUpdate)
                                .addGap(76, 76, 76)
                                .addComponent(btnDelete)
                                .addGap(69, 69, 69)
                                .addComponent(btnClear))
                            .addGroup(pnlFormLayout.createSequentialGroup()
                                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFldObjectName, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblErrorMsgObjectName, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(40, 40, 40)
                                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFldObjectType, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblErrorMsgObjectType, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(45, 45, 45)
                                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblErrorMsgCreator, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFldCreator, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(pnlFormLayout.createSequentialGroup()
                        .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFldStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblErrorMsgStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(64, 64, 64)
                        .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFldOrigin, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblErrorMsgOrigin, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFldCondition, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblErrorMsgCondition, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblErrorMsgFloor, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFldFloor, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlFormLayout.setVerticalGroup(
            pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFormLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFldObjectId, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFldObjectName, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFldObjectType, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFldCreator, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblErrorMsgObjectName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblErrorMsgObjectId, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblErrorMsgObjectType, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblErrorMsgCreator, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFldStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFldOrigin, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFldCondition, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFldFloor, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblErrorMsgStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblErrorMsgOrigin, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblErrorMsgCondition, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblErrorMsgFloor, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(txtFldRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAddObject, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblErrorMsgRoomNo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlManageObjectsLayout = new javax.swing.GroupLayout(pnlManageObjects);
        pnlManageObjects.setLayout(pnlManageObjectsLayout);
        pnlManageObjectsLayout.setHorizontalGroup(
            pnlManageObjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblManageBojectsHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlForm, javax.swing.GroupLayout.DEFAULT_SIZE, 1300, Short.MAX_VALUE)
            .addGroup(pnlManageObjectsLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(pnlManageObjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(spTblObjects, javax.swing.GroupLayout.PREFERRED_SIZE, 1168, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlManageObjectsLayout.setVerticalGroup(
            pnlManageObjectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlManageObjectsLayout.createSequentialGroup()
                .addComponent(lblManageBojectsHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(spTblObjects, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(pnlForm, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        spTblObjects.getAccessibleContext().setAccessibleParent(spTblObjects);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(java.awt.Color.black);
        setIconImages(null);
        setLocation(new java.awt.Point(100, 50));
        setMaximumSize(new java.awt.Dimension(1300, 720));
        setMinimumSize(new java.awt.Dimension(1300, 720));
        setPreferredSize(new java.awt.Dimension(1300, 720));

        pnlLoadingScreen.setBackground(new java.awt.Color(0, 0, 0));
        pnlLoadingScreen.setForeground(new java.awt.Color(255, 255, 255));
        pnlLoadingScreen.setToolTipText("");
        pnlLoadingScreen.setMaximumSize(new java.awt.Dimension(1300, 700));
        pnlLoadingScreen.setMinimumSize(new java.awt.Dimension(1300, 700));
        pnlLoadingScreen.setPreferredSize(new java.awt.Dimension(1300, 700));
        pnlLoadingScreen.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblloading.setFont(new java.awt.Font("Calibri", 1, 48)); // NOI18N
        lblloading.setForeground(new java.awt.Color(255, 255, 255));
        lblloading.setText("Loading.......");
        pnlLoadingScreen.add(lblloading, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 610, 350, -1));

        prgBarLoadingScreen.setBackground(new java.awt.Color(255, 51, 0));
        prgBarLoadingScreen.setToolTipText("");
        pnlLoadingScreen.add(prgBarLoadingScreen, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 580, 370, 20));

        lblLoadingTitle.setBackground(new java.awt.Color(255, 255, 255));
        lblLoadingTitle.setFont(new java.awt.Font("Monotype Corsiva", 3, 90)); // NOI18N
        lblLoadingTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblLoadingTitle.setText("MUSEMO");
        pnlLoadingScreen.add(lblLoadingTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 620, 200));

        lblLoadingScreenGif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/musemo/resources/loading screen.gif"))); // NOI18N
        pnlLoadingScreen.add(lblLoadingScreenGif, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 1080, 750));

        lblCopyRight.setBackground(new java.awt.Color(255, 255, 255));
        lblCopyRight.setForeground(new java.awt.Color(255, 255, 255));
        lblCopyRight.setText("@Mimo @Viom");
        pnlLoadingScreen.add(lblCopyRight, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 640, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlLoadingScreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlLoadingScreen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdminLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminLoginActionPerformed
        loadScreen("AdminLoginScreen"); // Load the admin login screen
    }//GEN-LAST:event_btnAdminLoginActionPerformed

    private void btnBackToHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToHomeActionPerformed
        loadScreen("HomeScreen"); // Load the home screen
    }//GEN-LAST:event_btnBackToHomeActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // Get the username and password input
        String username = txtFldAdminLogin.getText();
        String password = new String(pwdFldAdminLogin.getPassword());

        // Check if username or password is empty
        if (username.isEmpty() || password.isEmpty()) {
            lblLoginError.setText("Please enter your username and password.");
        } 
        // Check if username and password are incorrect
        else if (!username.equals("v") || !password.equals("v")) {
            lblLoginError.setText("Username and password mismatch.");
        } 
        // If credentials are correct, proceed to load the main screen
        else {
            lblLoginError.setText(""); // Clear any previous error messages
            loadScreen("DashboardScreen"); // Load the main screen
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void txtFldAdminLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFldAdminLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFldAdminLoginActionPerformed

    private void btnManageObjectsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageObjectsActionPerformed
        loadScreen("ObjectManagementScreen");
    }//GEN-LAST:event_btnManageObjectsActionPerformed

    private void pwdFldAdminLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdFldAdminLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwdFldAdminLoginActionPerformed

    private void txtFldObjectIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFldObjectIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFldObjectIdActionPerformed

    private void btnAddObjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddObjectActionPerformed
        boolean isValid = true;
        // Validate Object ID
        isValid &= validateField(txtFldObjectId, "Object ID", lblErrorMsgObjectName, "Must be 3-digit number.",
                errorColor, greenColor, ValidationUtil.isValidObjectId(Integer.parseInt(txtFldObjectId.getText()))
        );

        // Validate Object Name
        isValid &= validateField(
                txtFldObjectName, "Object Name", lblErrorMsgObjectName, "Must contain only alphabets.",
                errorColor, greenColor, ValidationUtil.isValidName(txtFldObjectName.getText())
        );

        // Validate Object Type
        isValid &= validateField(
            txtFldObjectType, "Object Type", lblErrorMsgObjectType, "Must be Painting, Sculpture, Artifact, or Other.",
            errorColor, greenColor, ValidationUtil.isValidObjectType(txtFldObjectType.getText())
        );

        // Validate Creator
        isValid &= validateField(
            txtFldCreator, "Creator", lblErrorMsgCreator, "Must contain only alphabets.",
            errorColor, greenColor, ValidationUtil.isValidName(txtFldCreator.getText())
        );

        // Validate Status
        isValid &= validateField(
            txtFldStatus, "Status", lblErrorMsgStatus, "Must be Permanent or Temporary.",
            errorColor, greenColor, ValidationUtil.isValidStatus(txtFldStatus.getText())
        );

        // Validate Origin
        isValid &= validateField(
            txtFldOrigin, "Origin", lblErrorMsgOrigin, "Must contain only alphabets.",
            errorColor, greenColor, ValidationUtil.isValidName(txtFldOrigin.getText())
        );

        // Validate Condition
        isValid &= validateField(
            txtFldCondition, "Condition", lblErrorMsgCondition, "Must be Excellent, Good, Bad, Needs Restoration, or Damaged.",
            errorColor, greenColor, ValidationUtil.isValidCondition(txtFldCondition.getText())
        );

        // Validate Floor
        try{
            isValid &= validateField(
                txtFldFloor, "Floor", lblErrorMsgFloor, "Must be a number between 1 and 5.",
                errorColor, greenColor, ValidationUtil.isValidFloor(Short.parseShort(txtFldFloor.getText()))
            );
        
        } catch(NumberFormatException e) {
            validateField(
                txtFldFloor, "Floor", lblErrorMsgFloor, "Must be a number between 1 and 5.",
                errorColor, greenColor, false
            );
        }

        // Validate Room Number
        try{
            isValid &= validateField(
                txtFldRoom, "Room Number", lblErrorMsgRoomNo, "Must be a number between 1 and 7.",
                errorColor, greenColor, ValidationUtil.isValidRoom(Short.parseShort(txtFldRoom.getText()))
            );
        } catch(NumberFormatException e) {
            validateField(
                txtFldRoom, "Room Number", lblErrorMsgRoomNo, "Must be a valid number",
                errorColor, greenColor, false
            );
        }
        
        if (isValid) {
            // Create a ObjectModel instance
            ObjectModel newObject = new ObjectModel(
                    Integer.parseInt(txtFldObjectId.getText().trim()),
                    txtFldObjectName.getText().trim(),
                    txtFldObjectType.getText().trim(),
                    txtFldCreator.getText().trim(),
                    txtFldStatus.getText().trim(),
                    txtFldOrigin.getText().trim(),
                    txtFldCondition.getText().trim(),
                    Short.parseShort(txtFldFloor.getText().trim()),
                    Short.parseShort(txtFldRoom.getText().trim())                    
            );

            // Check for duplicate Object ID
            if (checkDuplicateObject(newObject)) {
                txtFldObjectId.setBorder(createTitledBorder(errorColor, "Object ID"));
                showDialogBox("Object with this ID already exists.", "Duplicate Entry!", JOptionPane.WARNING_MESSAGE);
            } else {
                // Add the object if no duplicate is found
                objectList.add(newObject);
                clearObjectForm();
                loadListToTable(objectList);
                txtFldObjectId.setBorder(createTitledBorder(greenColor, "Object ID"));
                showDialogBox("Object added successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnAddObjectActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed

    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clearObjectForm();
    }//GEN-LAST:event_btnClearActionPerformed
    /**
     * Validates a single input field based on specific criteria and updates its
     * visual state.
     * 
     * @param textField
     * @param fieldName
     * @param errorLbl
     * @param errorMsg
     * @param errorColor
     * @param successColor
     * @param isValidFormat
     * @return 
     */
    private boolean validateField(JTextField textField, String fieldName, JLabel errorLbl, String errorMsg, Color errorColor, Color successColor, boolean isValidFormat) {
        if (ValidationUtil.isNullOrEmpty(textField.getText())) {
            textField.setBorder(createTitledBorder(errorColor, fieldName));
            errorLbl.setText("Field cannot be empty!");
            errorLbl.setVisible(true);
            return false;
        } else if (!isValidFormat) {
            textField.setBorder(createTitledBorder(errorColor, fieldName));
            errorLbl.setText(errorMsg);
            errorLbl.setVisible(true);
            return false;
        } else {
            textField.setBorder(createTitledBorder(successColor, fieldName));
            errorLbl.setVisible(false);
            return true;
        }
    }
    
    /**
     * Creates a custom TitledBorder with specified color and title.
     *
     * @param color the color for the border and title
     * @param title the title text for the border
     * @return a TitledBorder instance
     */
    private javax.swing.border.TitledBorder createTitledBorder(Color color, String title) {
        return javax.swing.BorderFactory.createTitledBorder(
                javax.swing.BorderFactory.createLineBorder(color, 2),
                title,
                javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
                javax.swing.border.TitledBorder.DEFAULT_POSITION,
                new java.awt.Font("Segoe UI", 1, 12),
                color
        );
    }
    
    private void txtFldConditionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFldConditionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFldConditionActionPerformed

    private void txtFldObjectNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFldObjectNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFldObjectNameActionPerformed

    private void txtFldObjectTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFldObjectTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFldObjectTypeActionPerformed

    private void txtFldCreatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFldCreatorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFldCreatorActionPerformed

    private void txtFldStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFldStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFldStatusActionPerformed

    private void txtFldOriginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFldOriginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFldOriginActionPerformed

    private void txtFldRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFldRoomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFldRoomActionPerformed

    private void txtFldFloorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFldFloorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFldFloorActionPerformed
    /**
     * Initializes the layout of the application by setting up the CardLayout
     * and adding panels for different screens. Each panel is uniquely
     * identified for easy navigation between screens.
     */
    private void initializeLayout() {
        cardLayout = new java.awt.CardLayout();
        getContentPane().setLayout(cardLayout);

        // Add panels with unique identifiers
        getContentPane().add(pnlLoadingScreen, "LoadingScreen");
        getContentPane().add(pnlAdminLoginScreen, "AdminLoginScreen");
        getContentPane().add(pnlHomeScreen, "HomeScreen");
        getContentPane().add(pnlAdminDashboardScreen, "DashboardScreen");
        getContentPane().add(pnlManageObjects, "ObjectManagementScreen");


        // Start with the loading screen
        loadScreen("LoadingScreen");
    }   
    /**
     * Initializes the Object data and Object Table.
     * Adds some Initial data into the Object List.
     */
    private void initializaData() {
        objectList = new LinkedList<>();
        // Registering sample objects
        enterObject(new ObjectModel(110, "Mona Lisa", "Painitng", "Leonardo da Vinci", "Permanent", "Italy", "Excellent", (short)1 ,(short)2));
        enterObject(new ObjectModel(140, "The Thinker", "Sculpture", "Auguste Robin", "Permanent", "France", "Good", (short)1 ,(short)5));
        enterObject(new ObjectModel(777, "Winged Victory", "Sculpture", "Unlnown", "Temporary", "Greece", "Damaged", (short)5 ,(short)7));
        enterObject(new ObjectModel(401, "Rosetta Stone", "Artifact", "Ancient Egyptians", "Permanent", "Egypt", "Needs Restoration", (short)02 ,(short)1));
        enterObject(new ObjectModel(242, "Starry Night", "Painitng", "Vincent van Gogh", "Temporary", "Netherlands", "Excellent", (short)3 ,(short)2));        
    }
    /**
     * Method to add object data to table from List. 
     * @param object 
     */
    private void enterObject(ObjectModel object){
        objectList.add(object);
        
        DefaultTableModel model = (DefaultTableModel) tblObject.getModel();
        model.addRow(new Object[]{
            object.getObjectID(), object.getObjectName(), object.getObjectType(),
            object.getCreator(), object.getStatus(),object.getOrigin(), 
            object.getCondition(), object.getFloor(), object.getRoomNo()
        });
    }
    /**
     * Switches the application screen to the specified screen name.
     *
     * @param screenName The name of the screen to display.
     */
    private void loadScreen(String screenName) {
        cardLayout.show(getContentPane(), screenName);
    }
    /**
     * Simulates the loading progress using a SwingWorker thread. Updates a
     * progress bar incrementally and switches to the login screen upon
     * completion.
     */
    private void startProgress() {
        javax.swing.SwingWorker<Void, Integer> worker = new javax.swing.SwingWorker<>() {
            @Override
            protected Void doInBackground() throws Exception {
                for (int i = 0; i <= 100; i++) {
                    Thread.sleep(100); // Simulated delay for progress bar
                    publish(i); // Publish progress
                }
                return null;
            }

            @Override
            protected void process(java.util.List<Integer> chunks) {
                int progress = chunks.get(chunks.size() - 1);
                prgBarLoadingScreen.setValue(progress);
            }

            @Override
            protected void done() {
                loadScreen("HomeScreen"); // Switch to login screen
            }
        };
        worker.execute(); // Start the worker thread
    }
    
    /**
     * Populates the JTable with the current list of Object records. 
     * 
     */
    private void loadListToTable(List<ObjectModel> objectList) {
        DefaultTableModel model = (DefaultTableModel) tblObject.getModel();

        // Clear existing rows if needed
        //model.setRowCount(0);

        // Populate the table with object data
        objectList.forEach(object -> model.addRow(new Object[]{
            object.getObjectID(),
            object.getObjectName(),
            object.getObjectType(),
            object.getCreator(),
            object.getStatus(),
            object.getOrigin(),
            object.getCondition(),
            object.getFloor(),
            object.getRoomNo(),

        }));
    }
    
    /**
     * Method to show dialogue box with entered message, title and message type.
     * @param message
     * @param title
     * @param messageType 
     */
    private void showDialogBox(String message, String title, int messageType) {
        JOptionPane.showMessageDialog(this, message, title, messageType);
    }
    
    /**
     * Method to check if duplicate object is entered.
     * @param object ObjectModel object to check for duplicates
     * @return true id duplicate is found
     */
    private boolean checkDuplicateObject(ObjectModel object) {
        return objectList.stream()
                .anyMatch(existingObject
                        -> existingObject.getObjectID() == object.getObjectID());
    }
    
    /**
     * Method to clear all the entered data from the text fields all at once
     */
    private void clearObjectForm() {
        txtFldObjectId.setText("");
        txtFldObjectName.setText("");
        txtFldObjectType.setText("");
        txtFldCreator.setText("");
        txtFldOrigin.setText("");
        txtFldStatus.setText("");
        txtFldCondition.setText("");
        txtFldFloor.setText("");
        txtFldRoom.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Musemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Musemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Musemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Musemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Musemo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddObject;
    private javax.swing.JButton btnAdminLogin;
    private javax.swing.JButton btnBackToHome;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnManageObjects;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblAboutUsSlogan;
    private javax.swing.JLabel lblAboutUsTitle;
    private javax.swing.JLabel lblCopyRight;
    private javax.swing.JLabel lblDashboard;
    private javax.swing.JLabel lblDashboardTitle;
    private javax.swing.JLabel lblErrorMsgCondition;
    private javax.swing.JLabel lblErrorMsgCreator;
    private javax.swing.JLabel lblErrorMsgFloor;
    private javax.swing.JLabel lblErrorMsgObjectId;
    private javax.swing.JLabel lblErrorMsgObjectName;
    private javax.swing.JLabel lblErrorMsgObjectType;
    private javax.swing.JLabel lblErrorMsgOrigin;
    private javax.swing.JLabel lblErrorMsgRoomNo;
    private javax.swing.JLabel lblErrorMsgStatus;
    private javax.swing.JLabel lblFounderHeader;
    private javax.swing.JLabel lblFounderMessage;
    private javax.swing.JLabel lblHomePageHeader;
    private javax.swing.JLabel lblHomePageHeader1;
    private javax.swing.JLabel lblHomePageWelcome;
    private javax.swing.JLabel lblLoadingScreenGif;
    private javax.swing.JLabel lblLoadingTitle;
    private javax.swing.JLabel lblLoginError;
    private javax.swing.JLabel lblLoginIcon;
    private javax.swing.JLabel lblManageBojectsHeader;
    private javax.swing.JLabel lblloading;
    private javax.swing.JPanel pnlAboutPage;
    private javax.swing.JPanel pnlAdminDashboardScreen;
    private javax.swing.JPanel pnlAdminLoginScreen;
    private javax.swing.JPanel pnlForm;
    private javax.swing.JPanel pnlHome;
    private javax.swing.JPanel pnlHomeScreen;
    private javax.swing.JPanel pnlLoadingScreen;
    private javax.swing.JPanel pnlManageObjects;
    private javax.swing.JProgressBar prgBarLoadingScreen;
    private javax.swing.JPasswordField pwdFldAdminLogin;
    private javax.swing.JScrollPane spTblObjects;
    private javax.swing.JTable tblObject;
    private javax.swing.JTextField txtFldAdminLogin;
    private javax.swing.JTextField txtFldCondition;
    private javax.swing.JTextField txtFldCreator;
    private javax.swing.JTextField txtFldFloor;
    private javax.swing.JTextField txtFldObjectId;
    private javax.swing.JTextField txtFldObjectName;
    private javax.swing.JTextField txtFldObjectType;
    private javax.swing.JTextField txtFldOrigin;
    private javax.swing.JTextField txtFldRoom;
    private javax.swing.JTextField txtFldStatus;
    // End of variables declaration//GEN-END:variables
}
