package com.musemo.view;

import com.musemo.controller.ValidationUtil;
import com.musemo.model.ArtifactModel;
import java.awt.Color;
import java.util.LinkedList;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Viom Shrestha
 */
public class Musemo extends javax.swing.JFrame {

    private List<ArtifactModel> artifactList;
    private java.awt.CardLayout cardLayout;
    private final ValidationUtil validationUtil;
    private final Color errorColor = new Color(255, 51, 0);
    private final Color greenColor = new Color(0, 255, 102);

    /**
     * Creates new form Musemo
     */
    public Musemo() {
        initComponents();
        validationUtil = new ValidationUtil();
        initializeLayout(); // Sets up CardLayout and pages
        initializaData(); // Initialize Objct data and Object table
        startProgress(); // Simulates the loading bar
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHomeScreen = new javax.swing.JPanel();
        lblHomePageHeader = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        scrlPaneHome = new javax.swing.JScrollPane();
        pnlHome = new javax.swing.JPanel();
        btnAdminLogin = new javax.swing.JButton();
        btnBookNowPH = new javax.swing.JButton();
        lblHomePageWelcome1 = new javax.swing.JLabel();
        pnlAboutPage = new javax.swing.JPanel();
        lblFounderMessage = new javax.swing.JLabel();
        lblAboutUsTitle = new javax.swing.JLabel();
        lblAboutUsSlogan = new javax.swing.JLabel();
        lblFounderHeader = new javax.swing.JLabel();
        pnlAdminLoginScreen = new javax.swing.JPanel();
        btnBackToHome = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtFldAdminLogin = new javax.swing.JTextField();
        pwdFldAdminLogin = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        lblLoginError = new javax.swing.JLabel();
        lblLoginIcon = new javax.swing.JLabel();
        pnlAdminDashboardScreen = new javax.swing.JPanel();
        lblHomePageHeader1 = new javax.swing.JLabel();
        lblDashboardTitle = new javax.swing.JLabel();
        lblDashboard = new javax.swing.JLabel();
        btnManageObjects = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        pnlManageArtifacts = new javax.swing.JPanel();
        lblManageBojectsHeader = new javax.swing.JLabel();
        spTblObjects = new javax.swing.JScrollPane();
        tblArtifact = new javax.swing.JTable();
        lblTabletitle = new javax.swing.JLabel();
        pnlForm = new javax.swing.JPanel();
        txtFldArtifactId = new javax.swing.JTextField();
        txtFldArtifactName = new javax.swing.JTextField();
        cmbBoxArtifactType = new javax.swing.JComboBox<>();
        txtFldCreator = new javax.swing.JTextField();
        txtFldStatus = new javax.swing.JTextField();
        txtFldOrigin = new javax.swing.JTextField();
        txtFldRoom = new javax.swing.JTextField();
        txtFldFloor = new javax.swing.JTextField();
        cmbBoxCondition = new javax.swing.JComboBox<>();
        btnAddArtifact = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        lblErrorMsgArtifactName = new javax.swing.JLabel();
        lblErrorMsgArtifactId = new javax.swing.JLabel();
        lblErrorMsgArtifactType = new javax.swing.JLabel();
        lblErrorMsgCreator = new javax.swing.JLabel();
        lblErrorMsgStatus = new javax.swing.JLabel();
        lblErrorMsgOrigin = new javax.swing.JLabel();
        lblErrorMsgCondition = new javax.swing.JLabel();
        lblErrorMsgFloor = new javax.swing.JLabel();
        lblErrorMsgRoomNo = new javax.swing.JLabel();
        btnBackToHome1 = new javax.swing.JButton();
        pnlLoadingScreen = new javax.swing.JPanel();
        lblloading = new javax.swing.JLabel();
        prgBarLoadingScreen = new javax.swing.JProgressBar();
        lblLoadingTitle = new javax.swing.JLabel();
        lblLoadingScreenGif = new javax.swing.JLabel();
        lblCopyRight = new javax.swing.JLabel();

        pnlHomeScreen.setBackground(new java.awt.Color(1, 0, 59));
        pnlHomeScreen.setMaximumSize(new java.awt.Dimension(1300, 700));
        pnlHomeScreen.setMinimumSize(new java.awt.Dimension(1300, 700));

        lblHomePageHeader.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/musemo/resources/AllPageHeader.png"))); // NOI18N

        jTabbedPane1.setBackground(new java.awt.Color(1, 127, 132));
        jTabbedPane1.setMaximumSize(new java.awt.Dimension(1300, 500));
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(1300, 500));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(1300, 500));

        scrlPaneHome.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        pnlHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAdminLogin.setBackground(new java.awt.Color(153, 153, 255));
        btnAdminLogin.setFont(new java.awt.Font("Poor Richard", 1, 18)); // NOI18N
        btnAdminLogin.setForeground(new java.awt.Color(0, 0, 0));
        btnAdminLogin.setText("Admin");
        btnAdminLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminLoginActionPerformed(evt);
            }
        });
        pnlHome.add(btnAdminLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnBookNowPH.setBackground(new java.awt.Color(153, 153, 255));
        btnBookNowPH.setFont(new java.awt.Font("Poor Richard", 1, 18)); // NOI18N
        btnBookNowPH.setForeground(new java.awt.Color(0, 0, 0));
        btnBookNowPH.setText("Book Now");
        btnBookNowPH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookNowPHActionPerformed(evt);
            }
        });
        pnlHome.add(btnBookNowPH, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 630, 110, 40));

        lblHomePageWelcome1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/musemo/resources/HomePageImg.png"))); // NOI18N
        pnlHome.add(lblHomePageWelcome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        scrlPaneHome.setViewportView(pnlHome);

        jTabbedPane1.addTab("Home", scrlPaneHome);

        pnlAboutPage.setBackground(new java.awt.Color(9, 1, 59));
        pnlAboutPage.setPreferredSize(new java.awt.Dimension(1300, 700));

        lblFounderMessage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/musemo/resources/AboutPageMessage.jpg"))); // NOI18N

        lblAboutUsTitle.setBackground(new java.awt.Color(255, 255, 255));
        lblAboutUsTitle.setFont(new java.awt.Font("Poor Richard", 1, 36)); // NOI18N
        lblAboutUsTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblAboutUsTitle.setText("About Us");

        lblAboutUsSlogan.setBackground(new java.awt.Color(255, 255, 255));
        lblAboutUsSlogan.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        lblAboutUsSlogan.setForeground(new java.awt.Color(255, 255, 255));
        lblAboutUsSlogan.setText("\"Preserving the past to inspire the future, our museum is a gateway to history, culture, and discovery.\"");

        lblFounderHeader.setBackground(new java.awt.Color(255, 255, 255));
        lblFounderHeader.setFont(new java.awt.Font("Poor Richard", 1, 36)); // NOI18N
        lblFounderHeader.setForeground(new java.awt.Color(255, 255, 255));
        lblFounderHeader.setText("Message from the Founder:");

        javax.swing.GroupLayout pnlAboutPageLayout = new javax.swing.GroupLayout(pnlAboutPage);
        pnlAboutPage.setLayout(pnlAboutPageLayout);
        pnlAboutPageLayout.setHorizontalGroup(
            pnlAboutPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAboutPageLayout.createSequentialGroup()
                .addGroup(pnlAboutPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFounderMessage)
                    .addGroup(pnlAboutPageLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(lblFounderHeader)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAboutPageLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlAboutPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAboutPageLayout.createSequentialGroup()
                        .addComponent(lblAboutUsTitle)
                        .addGap(577, 577, 577))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAboutPageLayout.createSequentialGroup()
                        .addComponent(lblAboutUsSlogan)
                        .addGap(216, 216, 216))))
        );
        pnlAboutPageLayout.setVerticalGroup(
            pnlAboutPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAboutPageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAboutUsTitle)
                .addGap(18, 18, 18)
                .addComponent(lblAboutUsSlogan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 270, Short.MAX_VALUE)
                .addComponent(lblFounderHeader)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFounderMessage)
                .addGap(35, 35, 35))
        );

        jTabbedPane1.addTab("About", pnlAboutPage);

        javax.swing.GroupLayout pnlHomeScreenLayout = new javax.swing.GroupLayout(pnlHomeScreen);
        pnlHomeScreen.setLayout(pnlHomeScreenLayout);
        pnlHomeScreenLayout.setHorizontalGroup(
            pnlHomeScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblHomePageHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlHomeScreenLayout.setVerticalGroup(
            pnlHomeScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHomeScreenLayout.createSequentialGroup()
                .addComponent(lblHomePageHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 775, Short.MAX_VALUE))
        );

        pnlAdminLoginScreen.setBackground(new java.awt.Color(1, 0, 59));
        pnlAdminLoginScreen.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlAdminLoginScreen.setMaximumSize(new java.awt.Dimension(1300, 700));
        pnlAdminLoginScreen.setMinimumSize(new java.awt.Dimension(900, 600));
        pnlAdminLoginScreen.setPreferredSize(new java.awt.Dimension(1300, 700));

        btnBackToHome.setBackground(new java.awt.Color(255, 255, 255));
        btnBackToHome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBackToHome.setForeground(new java.awt.Color(102, 0, 153));
        btnBackToHome.setText("Back");
        btnBackToHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackToHomeActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Admin Login");

        txtFldAdminLogin.setBackground(new java.awt.Color(1, 0, 59));
        txtFldAdminLogin.setForeground(new java.awt.Color(153, 153, 255));
        txtFldAdminLogin.setText("v");
        txtFldAdminLogin.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255), 2), "Username", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(153, 153, 255))); // NOI18N
        txtFldAdminLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFldAdminLoginActionPerformed(evt);
            }
        });

        pwdFldAdminLogin.setBackground(new java.awt.Color(1, 0, 59));
        pwdFldAdminLogin.setForeground(new java.awt.Color(234, 192, 32));
        pwdFldAdminLogin.setText("v");
        pwdFldAdminLogin.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255), 2), "Password", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(153, 153, 255))); // NOI18N
        pwdFldAdminLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdFldAdminLoginActionPerformed(evt);
            }
        });

        btnLogin.setBackground(new java.awt.Color(255, 255, 255));
        btnLogin.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(0, 0, 0));
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        lblLoginError.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lblLoginError.setForeground(new java.awt.Color(255, 0, 0));
        lblLoginError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblLoginIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/musemo/resources/LoginImg.jpg"))); // NOI18N

        javax.swing.GroupLayout pnlAdminLoginScreenLayout = new javax.swing.GroupLayout(pnlAdminLoginScreen);
        pnlAdminLoginScreen.setLayout(pnlAdminLoginScreenLayout);
        pnlAdminLoginScreenLayout.setHorizontalGroup(
            pnlAdminLoginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdminLoginScreenLayout.createSequentialGroup()
                .addGroup(pnlAdminLoginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAdminLoginScreenLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(pnlAdminLoginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBackToHome, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlAdminLoginScreenLayout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addGroup(pnlAdminLoginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtFldAdminLogin)
                                    .addComponent(pwdFldAdminLogin)
                                    .addComponent(btnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                                    .addGroup(pnlAdminLoginScreenLayout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addComponent(jLabel2)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlAdminLoginScreenLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblLoginError, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)))
                .addGap(33, 33, 33)
                .addComponent(lblLoginIcon))
        );
        pnlAdminLoginScreenLayout.setVerticalGroup(
            pnlAdminLoginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdminLoginScreenLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btnBackToHome)
                .addGap(87, 87, 87)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLoginError, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFldAdminLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(pwdFldAdminLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(lblLoginIcon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pnlAdminDashboardScreen.setBackground(new java.awt.Color(1, 0, 59));
        pnlAdminDashboardScreen.setMaximumSize(new java.awt.Dimension(1300, 700));
        pnlAdminDashboardScreen.setMinimumSize(new java.awt.Dimension(1300, 700));
        pnlAdminDashboardScreen.setPreferredSize(new java.awt.Dimension(1300, 700));

        lblHomePageHeader1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/musemo/resources/AllPageHeader.png"))); // NOI18N

        lblDashboardTitle.setFont(new java.awt.Font("Poor Richard", 1, 36)); // NOI18N
        lblDashboardTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblDashboardTitle.setText("Dashboard");

        lblDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/musemo/resources/AdminDashBoard.jpg"))); // NOI18N

        btnManageObjects.setBackground(new java.awt.Color(255, 255, 255));
        btnManageObjects.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnManageObjects.setForeground(new java.awt.Color(0, 0, 0));
        btnManageObjects.setText("Manage Objects");
        btnManageObjects.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageObjectsActionPerformed(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(255, 255, 255));
        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(0, 0, 0));
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAdminDashboardScreenLayout = new javax.swing.GroupLayout(pnlAdminDashboardScreen);
        pnlAdminDashboardScreen.setLayout(pnlAdminDashboardScreenLayout);
        pnlAdminDashboardScreenLayout.setHorizontalGroup(
            pnlAdminDashboardScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblHomePageHeader1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlAdminDashboardScreenLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(lblDashboardTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnManageObjects)
                .addGap(47, 47, 47))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAdminDashboardScreenLayout.createSequentialGroup()
                .addComponent(lblDashboard)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlAdminDashboardScreenLayout.setVerticalGroup(
            pnlAdminDashboardScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdminDashboardScreenLayout.createSequentialGroup()
                .addComponent(lblHomePageHeader1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(pnlAdminDashboardScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAdminDashboardScreenLayout.createSequentialGroup()
                        .addGroup(pnlAdminDashboardScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnManageObjects)
                            .addComponent(btnLogout))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAdminDashboardScreenLayout.createSequentialGroup()
                        .addComponent(lblDashboardTitle)
                        .addGap(9, 9, 9)))
                .addComponent(lblDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pnlManageArtifacts.setBackground(new java.awt.Color(1, 0, 59));
        pnlManageArtifacts.setMaximumSize(new java.awt.Dimension(1300, 700));
        pnlManageArtifacts.setMinimumSize(new java.awt.Dimension(1300, 700));
        pnlManageArtifacts.setPreferredSize(new java.awt.Dimension(1300, 700));

        lblManageBojectsHeader.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/musemo/resources/AllPageHeader.png"))); // NOI18N

        tblArtifact.setBackground(new java.awt.Color(153, 153, 255));
        tblArtifact.setForeground(new java.awt.Color(0, 0, 0));
        tblArtifact.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Artifact ID", "Artifact Name", "Artifact Type", "Creator", "Status", "Origin", "Condition", "Floor", "Room"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Short.class, java.lang.Short.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblArtifact.setGridColor(new java.awt.Color(0, 0, 0));
        tblArtifact.setSelectionBackground(new java.awt.Color(102, 102, 255));
        tblArtifact.setSelectionForeground(new java.awt.Color(51, 255, 0));
        tblArtifact.setShowGrid(true);
        tblArtifact.getTableHeader().setReorderingAllowed(false);
        spTblObjects.setViewportView(tblArtifact);
        if (tblArtifact.getColumnModel().getColumnCount() > 0) {
            tblArtifact.getColumnModel().getColumn(0).setResizable(false);
            tblArtifact.getColumnModel().getColumn(1).setResizable(false);
            tblArtifact.getColumnModel().getColumn(2).setResizable(false);
            tblArtifact.getColumnModel().getColumn(3).setResizable(false);
            tblArtifact.getColumnModel().getColumn(4).setResizable(false);
            tblArtifact.getColumnModel().getColumn(5).setResizable(false);
            tblArtifact.getColumnModel().getColumn(6).setResizable(false);
            tblArtifact.getColumnModel().getColumn(7).setResizable(false);
            tblArtifact.getColumnModel().getColumn(8).setResizable(false);
        }
        tblArtifact.getAccessibleContext().setAccessibleParent(tblArtifact);

        lblTabletitle.setFont(new java.awt.Font("Poor Richard", 1, 24)); // NOI18N
        lblTabletitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTabletitle.setText("Artifacts  Table");

        pnlForm.setBackground(new java.awt.Color(137, 136, 246));
        pnlForm.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Artifact Form", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Poor Richard", 1, 24), new java.awt.Color(255, 255, 255))); // NOI18N
        pnlForm.setMaximumSize(new java.awt.Dimension(1080, 960));
        pnlForm.setMinimumSize(new java.awt.Dimension(1080, 960));
        pnlForm.setPreferredSize(new java.awt.Dimension(900, 300));

        txtFldArtifactId.setBackground(new java.awt.Color(0, 0, 0));
        txtFldArtifactId.setForeground(new java.awt.Color(255, 255, 255));
        txtFldArtifactId.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255)), "Artifact Id", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        txtFldArtifactId.setCaretColor(new java.awt.Color(0, 102, 102));
        txtFldArtifactId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFldArtifactIdActionPerformed(evt);
            }
        });

        txtFldArtifactName.setBackground(new java.awt.Color(0, 0, 0));
        txtFldArtifactName.setForeground(new java.awt.Color(255, 255, 255));
        txtFldArtifactName.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255)), "Artifact Name", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        txtFldArtifactName.setCaretColor(new java.awt.Color(0, 102, 102));
        txtFldArtifactName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFldArtifactNameActionPerformed(evt);
            }
        });

        cmbBoxArtifactType.setBackground(new java.awt.Color(0, 0, 0));
        cmbBoxArtifactType.setForeground(new java.awt.Color(255, 255, 255));
        cmbBoxArtifactType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Painting", "Sculpture", "Relic", "Others" }));
        cmbBoxArtifactType.setSelectedIndex(-1);
        cmbBoxArtifactType.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Artifact Type", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        cmbBoxArtifactType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBoxArtifactTypeActionPerformed(evt);
            }
        });

        txtFldCreator.setBackground(new java.awt.Color(0, 0, 0));
        txtFldCreator.setForeground(new java.awt.Color(255, 255, 255));
        txtFldCreator.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255)), "Creator", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        txtFldCreator.setCaretColor(new java.awt.Color(0, 102, 102));
        txtFldCreator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFldCreatorActionPerformed(evt);
            }
        });

        txtFldStatus.setBackground(new java.awt.Color(0, 0, 0));
        txtFldStatus.setForeground(new java.awt.Color(255, 255, 255));
        txtFldStatus.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255)), "Status", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        txtFldStatus.setCaretColor(new java.awt.Color(0, 102, 102));
        txtFldStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFldStatusActionPerformed(evt);
            }
        });

        txtFldOrigin.setBackground(new java.awt.Color(0, 0, 0));
        txtFldOrigin.setForeground(new java.awt.Color(255, 255, 255));
        txtFldOrigin.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255)), "Origin", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        txtFldOrigin.setCaretColor(new java.awt.Color(0, 102, 102));
        txtFldOrigin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFldOriginActionPerformed(evt);
            }
        });

        txtFldRoom.setBackground(new java.awt.Color(0, 0, 0));
        txtFldRoom.setForeground(new java.awt.Color(255, 255, 255));
        txtFldRoom.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255)), "Room", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        txtFldRoom.setCaretColor(new java.awt.Color(0, 102, 102));
        txtFldRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFldRoomActionPerformed(evt);
            }
        });

        txtFldFloor.setBackground(new java.awt.Color(0, 0, 0));
        txtFldFloor.setForeground(new java.awt.Color(255, 255, 255));
        txtFldFloor.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255)), "Floor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        txtFldFloor.setCaretColor(new java.awt.Color(0, 102, 102));
        txtFldFloor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFldFloorActionPerformed(evt);
            }
        });

        cmbBoxCondition.setBackground(new java.awt.Color(0, 0, 0));
        cmbBoxCondition.setForeground(new java.awt.Color(255, 255, 255));
        cmbBoxCondition.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Excellent", "Good", "Bad", "Needs Restoration", "Damaged" }));
        cmbBoxCondition.setSelectedIndex(-1);
        cmbBoxCondition.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Condition", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        cmbBoxCondition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBoxConditionActionPerformed(evt);
            }
        });

        btnAddArtifact.setBackground(new java.awt.Color(153, 255, 204));
        btnAddArtifact.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAddArtifact.setForeground(new java.awt.Color(0, 0, 0));
        btnAddArtifact.setText("Add Artifact");
        btnAddArtifact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddArtifactActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(153, 255, 204));
        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(0, 0, 0));
        btnDelete.setText("Delete Artifact");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(153, 255, 204));
        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(0, 0, 0));
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(153, 255, 204));
        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnClear.setForeground(new java.awt.Color(0, 0, 0));
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        lblErrorMsgArtifactName.setForeground(new java.awt.Color(255, 255, 255));

        lblErrorMsgArtifactId.setForeground(new java.awt.Color(255, 255, 255));

        lblErrorMsgArtifactType.setForeground(new java.awt.Color(255, 255, 255));

        lblErrorMsgCreator.setForeground(new java.awt.Color(255, 255, 255));

        lblErrorMsgStatus.setForeground(new java.awt.Color(255, 255, 255));

        lblErrorMsgOrigin.setForeground(new java.awt.Color(255, 255, 255));

        lblErrorMsgCondition.setForeground(new java.awt.Color(255, 255, 255));

        lblErrorMsgFloor.setForeground(new java.awt.Color(255, 255, 255));

        lblErrorMsgRoomNo.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlFormLayout = new javax.swing.GroupLayout(pnlForm);
        pnlForm.setLayout(pnlFormLayout);
        pnlFormLayout.setHorizontalGroup(
            pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFormLayout.createSequentialGroup()
                        .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlFormLayout.createSequentialGroup()
                                .addComponent(txtFldCreator, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtFldStatus))
                            .addComponent(lblErrorMsgArtifactName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlFormLayout.createSequentialGroup()
                                .addComponent(txtFldArtifactId, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cmbBoxArtifactType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(txtFldArtifactName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlFormLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lblErrorMsgArtifactId, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblErrorMsgArtifactType, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlFormLayout.createSequentialGroup()
                                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtFldOrigin, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                                    .addComponent(lblErrorMsgCreator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblErrorMsgStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmbBoxCondition, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(659, 659, 659))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFormLayout.createSequentialGroup()
                        .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlFormLayout.createSequentialGroup()
                                .addComponent(lblErrorMsgFloor, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblErrorMsgRoomNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlFormLayout.createSequentialGroup()
                                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(pnlFormLayout.createSequentialGroup()
                                            .addComponent(lblErrorMsgOrigin, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(lblErrorMsgCondition, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlFormLayout.createSequentialGroup()
                                            .addComponent(txtFldFloor, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtFldRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlFormLayout.createSequentialGroup()
                                        .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(btnAddArtifact, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                                            .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(617, 617, 617))))
        );
        pnlFormLayout.setVerticalGroup(
            pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFormLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFldArtifactId, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbBoxArtifactType, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblErrorMsgArtifactId, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblErrorMsgArtifactType, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtFldArtifactName, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblErrorMsgArtifactName, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFldStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFldCreator, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblErrorMsgStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblErrorMsgCreator, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtFldOrigin, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlFormLayout.createSequentialGroup()
                        .addComponent(cmbBoxCondition, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblErrorMsgOrigin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblErrorMsgCondition, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFldFloor, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFldRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblErrorMsgRoomNo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblErrorMsgFloor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddArtifact, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(289, 289, 289))
        );

        btnBackToHome1.setBackground(new java.awt.Color(255, 255, 255));
        btnBackToHome1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBackToHome1.setForeground(new java.awt.Color(102, 0, 153));
        btnBackToHome1.setText("Back");
        btnBackToHome1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackToHome1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlManageArtifactsLayout = new javax.swing.GroupLayout(pnlManageArtifacts);
        pnlManageArtifacts.setLayout(pnlManageArtifactsLayout);
        pnlManageArtifactsLayout.setHorizontalGroup(
            pnlManageArtifactsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlManageArtifactsLayout.createSequentialGroup()
                .addGroup(pnlManageArtifactsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlManageArtifactsLayout.createSequentialGroup()
                        .addComponent(lblManageBojectsHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(pnlManageArtifactsLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(pnlManageArtifactsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTabletitle, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlManageArtifactsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnBackToHome1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(spTblObjects, javax.swing.GroupLayout.PREFERRED_SIZE, 805, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)))
                .addComponent(pnlForm, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlManageArtifactsLayout.setVerticalGroup(
            pnlManageArtifactsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlManageArtifactsLayout.createSequentialGroup()
                .addComponent(lblManageBojectsHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(pnlManageArtifactsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTabletitle)
                    .addComponent(btnBackToHome1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(spTblObjects, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 74, Short.MAX_VALUE))
            .addComponent(pnlForm, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        spTblObjects.getAccessibleContext().setAccessibleParent(spTblObjects);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(java.awt.Color.black);
        setIconImages(null);
        setLocation(new java.awt.Point(100, 50));
        setMaximumSize(new java.awt.Dimension(1300, 720));
        setMinimumSize(new java.awt.Dimension(1300, 720));
        setPreferredSize(new java.awt.Dimension(1300, 720));

        pnlLoadingScreen.setBackground(new java.awt.Color(0, 0, 0));
        pnlLoadingScreen.setForeground(new java.awt.Color(255, 255, 255));
        pnlLoadingScreen.setToolTipText("");
        pnlLoadingScreen.setMaximumSize(new java.awt.Dimension(1300, 700));
        pnlLoadingScreen.setMinimumSize(new java.awt.Dimension(1300, 700));
        pnlLoadingScreen.setPreferredSize(new java.awt.Dimension(1300, 700));
        pnlLoadingScreen.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblloading.setFont(new java.awt.Font("Calibri", 1, 48)); // NOI18N
        lblloading.setForeground(new java.awt.Color(255, 255, 255));
        lblloading.setText("Loading.......");
        pnlLoadingScreen.add(lblloading, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 610, 350, -1));

        prgBarLoadingScreen.setBackground(new java.awt.Color(255, 51, 0));
        prgBarLoadingScreen.setToolTipText("");
        pnlLoadingScreen.add(prgBarLoadingScreen, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 580, 370, 20));

        lblLoadingTitle.setBackground(new java.awt.Color(255, 255, 255));
        lblLoadingTitle.setFont(new java.awt.Font("Monotype Corsiva", 3, 90)); // NOI18N
        lblLoadingTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblLoadingTitle.setText("MUSEMO");
        pnlLoadingScreen.add(lblLoadingTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 620, 200));

        lblLoadingScreenGif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/musemo/resources/loading screen.gif"))); // NOI18N
        pnlLoadingScreen.add(lblLoadingScreenGif, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 1080, 700));

        lblCopyRight.setBackground(new java.awt.Color(255, 255, 255));
        lblCopyRight.setForeground(new java.awt.Color(255, 255, 255));
        lblCopyRight.setText("@Mimo @Viom");
        pnlLoadingScreen.add(lblCopyRight, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 640, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlLoadingScreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlLoadingScreen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackToHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToHomeActionPerformed
        loadScreen("HomeScreen"); // Load the home screen
    }//GEN-LAST:event_btnBackToHomeActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // Get the username and password input
        String username = txtFldAdminLogin.getText();
        String password = new String(pwdFldAdminLogin.getPassword());

        // Check if username or password is empty
        if (username.isEmpty() || password.isEmpty()) {
            lblLoginError.setText("Please enter your username and password.");
        } // Check if username and password are incorrect
        else if (!username.equals("v") || !password.equals("v")) {
            lblLoginError.setText("Username and password mismatch.");
        } // If credentials are correct, proceed to load the main screen
        else {
            lblLoginError.setText(""); // Clear any previous error messages
            loadScreen("DashboardScreen"); // Load the main screen
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void txtFldAdminLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFldAdminLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFldAdminLoginActionPerformed

    private void btnManageObjectsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageObjectsActionPerformed
        loadScreen("ObjectManagementScreen");
    }//GEN-LAST:event_btnManageObjectsActionPerformed

    private void pwdFldAdminLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdFldAdminLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwdFldAdminLoginActionPerformed

    private void txtFldArtifactIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFldArtifactIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFldArtifactIdActionPerformed

    private void btnAddArtifactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddArtifactActionPerformed
        addArtifact();
    }//GEN-LAST:event_btnAddArtifactActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        deleteArtifact();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        updateArtifact();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clearArtifactForm();
    }//GEN-LAST:event_btnClearActionPerformed
    /**
     * Validates a single input field based on specific criteria and updates its
     * visual state.
     *
     * @param textField
     * @param fieldName
     * @param errorLbl
     * @param errorMsg
     * @param errorColor
     * @param successColor
     * @param isValidFormat
     * @return
     */
    private boolean validateField(JTextField textField, String fieldName, JLabel errorLbl, String errorMsg, Color errorColor, Color successColor, boolean isValidFormat) {
        if (ValidationUtil.isNullOrEmpty(textField.getText())) {
            textField.setBorder(createTitledBorder(errorColor, fieldName));
            errorLbl.setText("Field cannot be empty!");
            errorLbl.setVisible(true);
            return false;
        } else if (!isValidFormat) {
            textField.setBorder(createTitledBorder(errorColor, fieldName));
            errorLbl.setText(errorMsg);
            errorLbl.setVisible(true);
            return false;
        } else {
            textField.setBorder(createTitledBorder(successColor, fieldName));
            errorLbl.setVisible(false);
            return true;
        }
    }

    private boolean validateComboBox(JComboBox<?> comboBox, String fieldName, JLabel errorLbl, String errorMsg, Color errorColor, Color successColor, boolean isValidFormat) {
        if (comboBox.getSelectedIndex() == -1) { // No valid selection
            comboBox.setBorder(createTitledBorder(errorColor, fieldName));
            errorLbl.setText(errorMsg);
            errorLbl.setVisible(true);
            return false;
        } else if (!isValidFormat) {
            comboBox.setBorder(createTitledBorder(errorColor, fieldName));
            errorLbl.setText(errorMsg);
            errorLbl.setVisible(true);
            return false;
        } else {
            comboBox.setBorder(createTitledBorder(successColor, fieldName));
            errorLbl.setVisible(false);
            return true;
        }
    }

    /**
     * Creates a custom TitledBorder with specified color and title.
     *
     * @param color the color for the border and title
     * @param title the title text for the border
     * @return a TitledBorder instance
     */
    private javax.swing.border.TitledBorder createTitledBorder(Color color, String title) {
        return javax.swing.BorderFactory.createTitledBorder(
                javax.swing.BorderFactory.createLineBorder(color, 2),
                title,
                javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
                javax.swing.border.TitledBorder.DEFAULT_POSITION,
                new java.awt.Font("Segoe UI", 1, 12),
                color
        );
    }

    private void txtFldArtifactNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFldArtifactNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFldArtifactNameActionPerformed

    private void txtFldCreatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFldCreatorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFldCreatorActionPerformed

    private void txtFldStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFldStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFldStatusActionPerformed

    private void txtFldOriginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFldOriginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFldOriginActionPerformed

    private void txtFldRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFldRoomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFldRoomActionPerformed

    private void txtFldFloorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFldFloorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFldFloorActionPerformed

    private void btnBackToHome1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToHome1ActionPerformed
        loadScreen("DashboardScreen");
    }//GEN-LAST:event_btnBackToHome1ActionPerformed

    private void cmbBoxArtifactTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBoxArtifactTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbBoxArtifactTypeActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        loadScreen("AdminLoginScreen");
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnAdminLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminLoginActionPerformed
        loadScreen("AdminLoginScreen"); // Load the admin login screen
    }//GEN-LAST:event_btnAdminLoginActionPerformed

    private void btnBookNowPHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookNowPHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBookNowPHActionPerformed

    private void cmbBoxConditionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBoxConditionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbBoxConditionActionPerformed
    /**
     * Initializes the layout of the application by setting up the CardLayout
     * and adding panels for different screens. Each panel is uniquely
     * identified for easy navigation between screens.
     */
    private void initializeLayout() {
        cardLayout = new java.awt.CardLayout();
        getContentPane().setLayout(cardLayout);

        // Add panels with unique identifiers
        getContentPane().add(pnlLoadingScreen, "LoadingScreen");
        getContentPane().add(pnlAdminLoginScreen, "AdminLoginScreen");
        getContentPane().add(pnlHomeScreen, "HomeScreen");
        getContentPane().add(pnlAdminDashboardScreen, "DashboardScreen");
        getContentPane().add(pnlManageArtifacts, "ObjectManagementScreen");

        // Start with the loading screen
        loadScreen("LoadingScreen");
    }

    /**
     * Initializes the Artifact data and Artifact Table. Adds some Initial data
     * into the Object List.
     */
    private void initializaData() {
        artifactList = new LinkedList<>();
        // Registering sample objects
        enterArtifact(new ArtifactModel(110, "Mona Lisa", "Painitng", "Leonardo da Vinci", "Permanent", "Italy", "Excellent", (short) 1, (short) 2));
        enterArtifact(new ArtifactModel(140, "The Thinker", "Sculpture", "Auguste Robin", "Permanent", "France", "Good", (short) 1, (short) 5));
        enterArtifact(new ArtifactModel(777, "Winged Victory", "Sculpture", "Unlnown", "Temporary", "Greece", "Damaged", (short) 5, (short) 7));
        enterArtifact(new ArtifactModel(401, "Rosetta Stone", "Relic", "Ancient Egyptians", "Permanent", "Egypt", "Needs Restoration", (short) 02, (short) 1));
        enterArtifact(new ArtifactModel(242, "Starry Night", "Painitng", "Vincent van Gogh", "Temporary", "Netherlands", "Excellent", (short) 3, (short) 2));
    }

    private void addArtifact() {
        boolean isValid = validateFields();

        if (isValid) {
            // Create a ArtifactModel instance
            ArtifactModel newArtifact = new ArtifactModel(
                    Integer.parseInt(txtFldArtifactId.getText().trim()),
                    txtFldArtifactName.getText().trim(),
                    cmbBoxArtifactType.getSelectedItem().toString().trim(),
                    txtFldCreator.getText().trim(),
                    txtFldStatus.getText().trim(),
                    txtFldOrigin.getText().trim(),
                    cmbBoxCondition.getSelectedItem().toString().trim(),
                    Short.parseShort(txtFldFloor.getText().trim()),
                    Short.parseShort(txtFldRoom.getText().trim())
            );

            // Check for duplicate Object ID
            if (checkDuplicateArtifact(newArtifact)) {
                txtFldArtifactId.setBorder(createTitledBorder(errorColor, "Object ID"));
                showDialogBox("Artifact with this ID already exists.", "Duplicate Entry!", JOptionPane.WARNING_MESSAGE);
            } else {
                // Add the Artifact if no duplicate is found
                artifactList.add(newArtifact);
                clearArtifactForm();
                loadListToTable(artifactList);
                txtFldArtifactId.setBorder(createTitledBorder(greenColor, "Object ID"));
                showDialogBox("Artifact added successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }

    /**
     * Method to add Artifact data to table from List.
     *
     * @param object
     */
    private void enterArtifact(ArtifactModel artifact) {
        artifactList.add(artifact);

        DefaultTableModel model = (DefaultTableModel) tblArtifact.getModel();
        model.addRow(new Object[]{
            artifact.getArtifactID(), artifact.getArtifactName(), artifact.getArtifactType(),
            artifact.getCreator(), artifact.getStatus(), artifact.getOrigin(),
            artifact.getCondition(), artifact.getFloor(), artifact.getRoomNo()
        });
    }

    private void updateArtifact() {
        boolean isValid = validateFields();

        if (isValid) {
            // Get the selected artifact ID
            int artifactId = Integer.parseInt(txtFldArtifactId.getText());
            for (ArtifactModel artifact : artifactList) { // artifactList is a List<Artifact>
                if (artifact.getArtifactID() == artifactId) {
                    artifact.setArtifactName(txtFldArtifactName.getText());
                    artifact.setArtifactType(cmbBoxArtifactType.getSelectedItem().toString());
                    artifact.setCreator(txtFldCreator.getText());
                    artifact.setOrigin(txtFldOrigin.getText());
                    artifact.setCondition(cmbBoxCondition.getSelectedItem().toString());
                    artifact.setStatus(txtFldStatus.getText());
                    artifact.setFloor(Short.parseShort(txtFldFloor.getText()));
                    artifact.setRoomNo(Short.parseShort(txtFldRoom.getText()));
                    loadListToTable(artifactList);
                } else {
                    showDialogBox("Artifact not found or update failed.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }

    /**
     * Method to delete the artifact with entered id.
     */
    private void deleteArtifact() {
        boolean isValid = true;
        // Validate if an ID is provided
        try {
            isValid &= validateField(txtFldArtifactId, "Artifact ID", lblErrorMsgArtifactId, "Must be 3-digit number.",
                    errorColor, greenColor, ValidationUtil.isValidObjectId(Integer.parseInt(txtFldArtifactId.getText()))
            );
        } catch (NumberFormatException e) {
            isValid &= validateField(txtFldArtifactId, "Artifact ID", lblErrorMsgArtifactId, "Enter the Id of the Artifact to be deleted!",
                    errorColor, greenColor, false
            );
        }
        if (isValid) {
            // Get the selected artifact ID
            int artifactId = Integer.parseInt(txtFldArtifactId.getText());
            // Confirm deletion with the user
            int confirm = JOptionPane.showConfirmDialog(this,
                    "Are you sure you want to delete the object with ID: " + artifactId + "?",
                    "Confirm Deletion",
                    JOptionPane.YES_NO_OPTION);

            if (confirm == JOptionPane.YES_OPTION) {
                // Perform deletion from the data
                boolean isDeleted = deleteFromList(artifactId);

                if (isDeleted) {
                    showDialogBox("Artifact successfully deleted.", "Success", JOptionPane.INFORMATION_MESSAGE);
                    clearArtifactForm(); // Clear the form if needed
                } else {
                    showDialogBox("Artifact not found or deletion failed.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }

    /**
     * Method to delete artifact from list
     *
     * @param artifactId
     * @return
     */
    private boolean deleteFromList(int artifactId) {
        for (ArtifactModel artifact : artifactList) { // artifactList is a List<Artifact>
            if (artifact.getArtifactID() == artifactId) {
                artifactList.remove(artifact);
                loadListToTable(artifactList);
                return true; // Successfully deleted
            }
        }
        return false; // Not found
    }

    /**
     * Switches the application screen to the specified screen name.
     *
     * @param screenName The name of the screen to display.
     */
    private void loadScreen(String screenName) {
        cardLayout.show(getContentPane(), screenName);
    }

    /**
     * Simulates the loading progress using a SwingWorker thread. Updates a
     * progress bar incrementally and switches to the login screen upon
     * completion.
     */
    private void startProgress() {
        javax.swing.SwingWorker<Void, Integer> worker = new javax.swing.SwingWorker<>() {
            @Override
            protected Void doInBackground() throws Exception {
                for (int i = 0; i <= 100; i++) {
                    Thread.sleep(10); // Simulated delay for progress bar
                    publish(i); // Publish progress
                }
                return null;
            }

            @Override
            protected void process(java.util.List<Integer> chunks) {
                int progress = chunks.get(chunks.size() - 1);
                prgBarLoadingScreen.setValue(progress);
            }

            @Override
            protected void done() {
                loadScreen("HomeScreen"); // Switch to login screen
            }
        };
        worker.execute(); // Start the worker thread
    }

    /**
     * Populates the JTable with the current list of Artifact records. And
     * clears the table contents before adding
     */
    private void loadListToTable(List<ArtifactModel> artifactList) {
        DefaultTableModel model = (DefaultTableModel) tblArtifact.getModel();

        // Clear existing rows if needed
        model.setRowCount(0);

        // Populate the table with object data
        artifactList.forEach(object -> model.addRow(new Object[]{
            object.getArtifactID(),
            object.getArtifactName(),
            object.getArtifactType(),
            object.getCreator(),
            object.getStatus(),
            object.getOrigin(),
            object.getCondition(),
            object.getFloor(),
            object.getRoomNo(),}));
    }

    /**
     * Method to show dialogue box with entered message, title and message type.
     *
     * @param message
     * @param title
     * @param messageType
     */
    private void showDialogBox(String message, String title, int messageType) {
        JOptionPane.showMessageDialog(this, message, title, messageType);
    }

    /**
     * Method to check if duplicate object is entered.
     *
     * @param object ObjectModel object to check for duplicates
     * @return true id duplicate is found
     */
    private boolean checkDuplicateArtifact(ArtifactModel artifact) {
        return artifactList.stream()
                .anyMatch(existingObject
                        -> existingObject.getArtifactID() == artifact.getArtifactID());
    }

    /**
     * Method to clear all the entered data from the text fields all at once
     */
    private void clearArtifactForm() {
        txtFldArtifactId.setText("");
        txtFldArtifactName.setText("");
        cmbBoxArtifactType.setSelectedIndex(-1);
        txtFldCreator.setText("");
        txtFldOrigin.setText("");
        txtFldStatus.setText("");
        cmbBoxCondition.setSelectedIndex(-1);
        txtFldFloor.setText("");
        txtFldRoom.setText("");
    }

    private boolean validateFields() {
        boolean isValid = true;
        // Validate Artifact ID
        try {
            isValid &= validateField(txtFldArtifactId, "Artifact ID", lblErrorMsgArtifactId, "Must be 3-digit number.",
                    errorColor, greenColor, ValidationUtil.isValidObjectId(Integer.parseInt(txtFldArtifactId.getText()))
            );
        } catch (NumberFormatException e) {
            isValid &= validateField(txtFldArtifactId, "Artifact ID", lblErrorMsgArtifactId, "Field cannot be empty",
                    errorColor, greenColor, false
            );
        }

        // Validate Artifact Name
        isValid &= validateField(txtFldArtifactName, "Artifact Name", lblErrorMsgArtifactName, "Must contain only alphabets.",
                errorColor, greenColor, ValidationUtil.isValidName(txtFldArtifactName.getText())
        );

        // Validate Artifact Type
        isValid &= validateComboBox(
                cmbBoxArtifactType, "Artifact Type", lblErrorMsgArtifactType, "Must Select Something.",
                errorColor, greenColor, ValidationUtil.isValidComboBoxSelection(cmbBoxArtifactType.getSelectedIndex())
        );

        // Validate Creator
        isValid &= validateField(
                txtFldCreator, "Creator", lblErrorMsgCreator, "Must contain only alphabets.",
                errorColor, greenColor, ValidationUtil.isValidName(txtFldCreator.getText())
        );

        // Validate Status
        isValid &= validateField(
                txtFldStatus, "Status", lblErrorMsgStatus, "Must be Permanent or Temporary.",
                errorColor, greenColor, ValidationUtil.isValidStatus(txtFldStatus.getText())
        );

        // Validate Origin
        isValid &= validateField(
                txtFldOrigin, "Origin", lblErrorMsgOrigin, "Must contain only alphabets.",
                errorColor, greenColor, ValidationUtil.isValidName(txtFldOrigin.getText())
        );
        // Validate Condition
        isValid &= validateComboBox(
                cmbBoxCondition, "Condition", lblErrorMsgCondition, "Must Select Something.",
                errorColor, greenColor, ValidationUtil.isValidComboBoxSelection(cmbBoxCondition.getSelectedIndex())
        );
        // Validate Floor
        try {
            isValid &= validateField(
                    txtFldFloor, "Floor", lblErrorMsgFloor, "Must be a number between 1 and 5.",
                    errorColor, greenColor, ValidationUtil.isValidFloor(Short.parseShort(txtFldFloor.getText()))
            );

        } catch (NumberFormatException e) {
            validateField(
                    txtFldFloor, "Floor", lblErrorMsgFloor, "Must be a valid number",
                    errorColor, greenColor, false
            );
        }

        // Validate Room Number
        try {
            isValid &= validateField(
                    txtFldRoom, "Room Number", lblErrorMsgRoomNo, "Must be a number between 1 and 7.",
                    errorColor, greenColor, ValidationUtil.isValidRoom(Short.parseShort(txtFldRoom.getText()))
            );
        } catch (NumberFormatException e) {
            validateField(
                    txtFldRoom, "Room Number", lblErrorMsgRoomNo, "Must be a valid number",
                    errorColor, greenColor, false
            );
        }
        return isValid;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Musemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Musemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Musemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Musemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Musemo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddArtifact;
    private javax.swing.JButton btnAdminLogin;
    private javax.swing.JButton btnBackToHome;
    private javax.swing.JButton btnBackToHome1;
    private javax.swing.JButton btnBookNowPH;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnManageObjects;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbBoxArtifactType;
    private javax.swing.JComboBox<String> cmbBoxCondition;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblAboutUsSlogan;
    private javax.swing.JLabel lblAboutUsTitle;
    private javax.swing.JLabel lblCopyRight;
    private javax.swing.JLabel lblDashboard;
    private javax.swing.JLabel lblDashboardTitle;
    private javax.swing.JLabel lblErrorMsgArtifactId;
    private javax.swing.JLabel lblErrorMsgArtifactName;
    private javax.swing.JLabel lblErrorMsgArtifactType;
    private javax.swing.JLabel lblErrorMsgCondition;
    private javax.swing.JLabel lblErrorMsgCreator;
    private javax.swing.JLabel lblErrorMsgFloor;
    private javax.swing.JLabel lblErrorMsgOrigin;
    private javax.swing.JLabel lblErrorMsgRoomNo;
    private javax.swing.JLabel lblErrorMsgStatus;
    private javax.swing.JLabel lblFounderHeader;
    private javax.swing.JLabel lblFounderMessage;
    private javax.swing.JLabel lblHomePageHeader;
    private javax.swing.JLabel lblHomePageHeader1;
    private javax.swing.JLabel lblHomePageWelcome1;
    private javax.swing.JLabel lblLoadingScreenGif;
    private javax.swing.JLabel lblLoadingTitle;
    private javax.swing.JLabel lblLoginError;
    private javax.swing.JLabel lblLoginIcon;
    private javax.swing.JLabel lblManageBojectsHeader;
    private javax.swing.JLabel lblTabletitle;
    private javax.swing.JLabel lblloading;
    private javax.swing.JPanel pnlAboutPage;
    private javax.swing.JPanel pnlAdminDashboardScreen;
    private javax.swing.JPanel pnlAdminLoginScreen;
    private javax.swing.JPanel pnlForm;
    private javax.swing.JPanel pnlHome;
    private javax.swing.JPanel pnlHomeScreen;
    private javax.swing.JPanel pnlLoadingScreen;
    private javax.swing.JPanel pnlManageArtifacts;
    private javax.swing.JProgressBar prgBarLoadingScreen;
    private javax.swing.JPasswordField pwdFldAdminLogin;
    private javax.swing.JScrollPane scrlPaneHome;
    private javax.swing.JScrollPane spTblObjects;
    private javax.swing.JTable tblArtifact;
    private javax.swing.JTextField txtFldAdminLogin;
    private javax.swing.JTextField txtFldArtifactId;
    private javax.swing.JTextField txtFldArtifactName;
    private javax.swing.JTextField txtFldCreator;
    private javax.swing.JTextField txtFldFloor;
    private javax.swing.JTextField txtFldOrigin;
    private javax.swing.JTextField txtFldRoom;
    private javax.swing.JTextField txtFldStatus;
    // End of variables declaration//GEN-END:variables
}
